version: "3.8"

services:
  frontend:
    build: ./ui
    image: dizplai-ui
    ports:
      - "3000:3000"
    restart: always
  api:
    build: ./api
    image: dizplai-api
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dizplaidb
    ports:
      - "5432:5432"
    networks:
      - dizplainetwork

networks:
  dizplainetwork:
    driver: bridge